/*
 * topics.h
 *
 *  Created on: 13 oct. 2022
 *      Author: fabri
 */

#ifndef MAIN_MQTT_MQTT_TOPICS_H_
#define MAIN_MQTT_MQTT_TOPICS_H_

#define GENERAL_TOPIC 				"MESPF"
#define SENSORS_TOPIC				"MESPF/SENS"
#define SCAN_TOPIC					"MESPF/SENS/SCAN"
#define INFO_TOPIC					"INFO"					//	MESPF/SENS/ESP32_XXXXX/SENSORNAME/N/INFO
#define ALERT_TOPIC					"ALERT"					//	MESPF/SENS/ESP32_XXXXX/SENSORNAME/N/ALERT
//#define PERSONAL_TOPIC			"ESP32_%CHIPID%"

#define SCAN_TOPIC					"MESPF/SENS/SCAN"
#define COMMANDS_TOPIC 				"CMD"					//  MESPF/SENS/ESP32_XXXXX/SENSORNAME/N/CMD
#define REFRESH_TOPIC				"CMD/REFRESH"			// 	MESPF/SENS/ESP32_XXXXX/SENSORNAME/N/CMD/REFRESH
#define SET_TOPIC					"CMD/SET"				// 	MESPF/SENS/ESP32_XXXXX/SENSORNAME/N/CMD/SET

#define USERS_TOPIC					"MESPF/USR"
#define SCAN_RESP_TOPIC				"SCAN"					//	MESPF/USR/USERNAME/SCAN
#define RESP_TOPIC					"RESP"					//	MESPF/USR/USERNAME/RESP
#define REFRESH_RESP_TOPIC			"REFRESH"				//	MESPF/USR/USERNAME/REFRESH



#endif /* MAIN_MQTT_MQTT_TOPICS_H_ */
